### ISSUE TITLE
Dragon burner spacer and backplate holes don't match

### ISSUE THREAD

**Issue by McPrince96** [Hellsparks/StealthChanger#13]
The bottom holes of the dragonburner spacer and backplate don't match the dragonburner cowl found in tapchanger.
Could be that i'm doing something wrong but i don't think so.

Cowl i printed:
https://github.com/viesturz/tapchanger/blob/main/Tapchanger/STL/Toolheads/DragonBurner/Cowling.stl

**Comment by TheSin-** [comment]
the issues isn't here, the one in the TapChanger repo is modified, you do not support the modified cowls, we only support the upstream cowls.

There is a merged version in one of the usermods, https://github.com/Hellsparks/StealthChanger/blob/main/UserMods/OstroMa/DB_Cowl_v8_with_TapChanger_Dock_Hooks.stl

Use that but it's a user mod and is not supported by the Stealthchanger team, we recommend using the original upstream cowl.
